# Generated by Django 2.2.12 on 2020-05-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.PositiveIntegerField(choices=[(0, 'Staff'), (1, 'Senior Staff'), (2, 'Manager')], default=0),
        ),
    ]
