# Generated by Django 2.2.12 on 2020-06-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.PositiveIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Select')], default=2)),
                ('legal_status', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('assigned', models.BooleanField(default=False)),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffChildManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='children.Child')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ChildRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('addtional_info', models.TextField(blank=True, null=True)),
                ('record_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField()),
                ('achievements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbook.Achievement')),
                ('activities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbook.Activity')),
                ('appointments_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbook.Appointment')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.Child')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbook.Education')),
                ('emotional_wellbeing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbook.EmotionalWellbeing')),
                ('health_hygiene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbook.HealthHygiene')),
                ('incidents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbook.Incident')),
                ('key_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbook.KeyWork')),
            ],
            options={
                'ordering': ['-date_created', '-id'],
            },
        ),
    ]
