# Generated by Django 2.2.12 on 2020-06-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
    ]
