# Generated by Django 2.2.12 on 2020-05-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_childrecord_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childrecord',
            options={'ordering': ['-date_created', '-id']},
        ),
    ]
