# Generated by Django 2.2.12 on 2020-05-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_auto_20200520_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrecord',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
