# Generated by Django 2.2.12 on 2020-06-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=200, null=True)),
                ('second', models.CharField(blank=True, max_length=200, null=True)),
                ('third', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_activities', models.CharField(blank=True, max_length=200, null=True)),
                ('other_activities', models.CharField(blank=True, max_length=200, null=True)),
                ('undertaken_activities', models.PositiveIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_appointment', models.PositiveIntegerField(default=4)),
                ('professional_appointment', models.PositiveIntegerField(default=4)),
                ('contact_visit_call', models.PositiveIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_attended', models.CharField(blank=True, max_length=200, null=True)),
                ('homework_completed', models.PositiveIntegerField(default=4)),
                ('educational_activity', models.CharField(blank=True, max_length=200, null=True)),
                ('school_contact', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionalWellbeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytime', models.PositiveIntegerField(blank=True, choices=[(0, 'AM'), (1, 'PM')])),
                ('measure', models.PositiveIntegerField(blank=True, choices=[(0, 'Positive'), (1, 'Negative')])),
                ('degree', models.PositiveIntegerField(blank=True, choices=[(0, 'Low'), (1, 'High')])),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=100)),
                ('meal_type', models.PositiveIntegerField(blank=True, choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner'), (3, 'Snacks')])),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('consequence', models.TextField(blank=True, null=True)),
                ('intervention', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_planned', models.PositiveIntegerField(default=4)),
                ('topic', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='HealthHygiene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytime', models.PositiveIntegerField(default=4)),
                ('medication_taken', models.PositiveIntegerField(choices=[(0, 'Yes'), (1, 'No')], default=4)),
                ('teeth_brushed', models.PositiveIntegerField(default=4)),
                ('bath_shower', models.PositiveIntegerField(default=4)),
                ('hair_washed', models.PositiveIntegerField(default=4)),
                ('diet_nutrition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workbook.Food')),
            ],
        ),
    ]
