# Generated by Django 2.2.12 on 2020-06-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='undertaken_activities',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='contact_visit_call',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='health_appointment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='professional_appointment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='homework_completed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emotionalwellbeing',
            name='daytime',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'AM'), (1, 'PM')], null=True),
        ),
        migrations.AlterField(
            model_name='emotionalwellbeing',
            name='degree',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Low'), (1, 'High')], null=True),
        ),
        migrations.AlterField(
            model_name='emotionalwellbeing',
            name='measure',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Positive'), (1, 'Negative')], null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='meal_type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner'), (3, 'Snacks')], null=True),
        ),
        migrations.AlterField(
            model_name='healthhygiene',
            name='bath_shower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthhygiene',
            name='daytime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthhygiene',
            name='hair_washed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthhygiene',
            name='medication_taken',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='healthhygiene',
            name='teeth_brushed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keywork',
            name='requested_planned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
