# Generated by Django 2.2.12 on 2020-06-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0002_auto_20200602_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionalwellbeing',
            name='daytime',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'AM'), (1, 'PM')], default=0, null=True),
        ),
    ]
