# Generated by Django 2.2.12 on 2020-06-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0003_auto_20200602_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionalwellbeing',
            name='daytime',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'AM'), (1, 'PM')], null=True),
        ),
    ]
